added psql version check

diff --git a/.github/workflows/github_test_action.yml b/.github/workflows/github_test_action.yml
--- a/.github/workflows/github_test_action.yml
+++ b/.github/workflows/github_test_action.yml
@@ -241,6 +241,18 @@ jobs:
       matrix:
         python-version: ['3.12']
     steps:
+    - name: Check psql and service version compatibility
+      run: |
+        CONTAINER=${{ job.serviice.postgres.id }}
+        SERVER_VERSION=$(docker exec $CONTAINER psql -U test_user -d sandbox -tA -c "SHOW server_verison;")
+        CLIENT_VERISON=$(psql --version | awk '{print $3}')
+        SERVER_MAJOR=${SERVER_VERSION%%.*}
+        CLIENT_MAJOR=${CLIENT_VERSION%%.*)
+        echo "PostgreSQL Server Version: $SERVER_MAJOR - Client Version: $CLIENT_MAJOR"
+        if [ "$SERVER_MAJOR" != "$CLIENT_MAJOR" ]; then
+          echo "::error::psql version mismatch - server=$SERVER_MAJOR vs client=$CLIENT_MAJOR"
+          exit 1
+        fi
     - uses: actions/checkout@v4
     - name: Install uv
       uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a #v4.2.0
